sudo: false
language: python

python:
  - "2.7"
#  - "3.7"

install: pip install tox-travis coverage

script:
  - tox
  - rvm install 2.3.1 && rvm use 2.3.1 && gem install danger --version '~> 4.0' && danger

after_success:
  - coverage combine tests/
  - bash <(curl -s https://codecov.io/bash)

branches:
  only: 
    - master

